{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.15-SNAPSHOT.jar",
          "url": "fabric-loom-1.15-SNAPSHOT.jar",
          "size": 1378553,
          "sha512": "064cc05260368469b61beaf9892f577e2fa3557deaa004f63db430a8802291d505376137737584d988118ec5b149fc6c6bf70bedbbcf67305216a7ae84544344",
          "sha256": "6d53854c393d65218912fbf8469e0dad4071efbbf99e7e975c9801b3184a28a3",
          "sha1": "9990cbd3ca89137b6cbb8d23717ad21c5ec62890",
          "md5": "89dffc5677a690d8987d5b1d8d830a21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.2.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.12.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.15-SNAPSHOT.jar",
          "url": "fabric-loom-1.15-SNAPSHOT.jar",
          "size": 1378553,
          "sha512": "064cc05260368469b61beaf9892f577e2fa3557deaa004f63db430a8802291d505376137737584d988118ec5b149fc6c6bf70bedbbcf67305216a7ae84544344",
          "sha256": "6d53854c393d65218912fbf8469e0dad4071efbbf99e7e975c9801b3184a28a3",
          "sha1": "9990cbd3ca89137b6cbb8d23717ad21c5ec62890",
          "md5": "89dffc5677a690d8987d5b1d8d830a21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.15-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.15-SNAPSHOT-sources.jar",
          "size": 825762,
          "sha512": "6bfa1cfcf64e0aea5d874e45f3e433eae92f7d0c6fc64a082433e2784b81da7653c2731409b5aea99d9e3f6eb445be3223fa5d65e4b73bfb668982cba51b09e2",
          "sha256": "65733fb41da5016c555b217983fa49edba96153f8e4bb980859d064f15220948",
          "sha1": "1c1faacee27c680c1e67492bc83657d814e91466",
          "md5": "09bb1f94f6ad5cb5b7e7c80831acb82f"
        }
      ]
    }
  ]
}
